### ISSUE TITLE
Quest Pods design tweak, and messages, comments, and roles errors

### ISSUE THREAD

**Issue by foresthoffman** [TheMacLab/game-on#102]
Some errors that have been around for a while, and a design change that needs to be made to the Pod Option page. 

Fixing the errors is fairly simple, we have several lines in the message and comment systems that attempt to access non-existent objects or non-existent elements.

When there are no pods already created, the Pod Option page has nothing to display, which makes it appear broken. To avoid confusion a message like, "There are no Pods to display, create one here." should be displayed and a link to the Pod category page should be provided.
#### Needed Changes
- Fix $roles error on login page (on line 212 in game-on.php v2.5.1)
- Fix offset error on dashboard (on line 8, 9, and 47 in go_messages.php v2.5.1)
- Fix comment author non-object error for comments (on line 8 in go_comments.php v2.5.1)
- Add message to Pod Options page when there are no Quest Pods (v2.5.1)
- Fix SQL error caused by a non-existent Pod slug being passed to the id parameter of the `go_task_pod` shortcode (in go_shortcodes.php inside the `go_task_pod_tasks` function on line 539 v2.5.1)
- Fix undefined variable error for $go_ahead on line 488 of task_shortcode.php ($go_ahead is defined inside an if-block on line 360 of task_shortcode.php in v2.5.1)
- Fix undefined index errors for the index “my-optional-pod” on lines 551, 613, and 614 in go_shortcodes.php (v2.5.1)
- Fix undefined index for null index on line 635 in go_shortcodes.php (v2.5.1)

**Comment by skocko** [comment]
Your attention to detail is amazing. #Respect

-----

Mike Skocko
Valhalla High School Mac Lab | 619 593-5446
New Media Arts Teacher | Adobe Education Leader
Website <http://maclab.guhsd.net> | Student Gallery
<https://www.behance.net/gallery/18308271/Mike-Skocko> | Game On
<http://maclab.guhsd.net/game-on/> | @themaclab
<http://twitter.com/themaclab>

**Comment by foresthoffman** [comment]
There is also a typo in the README, "Lovelying Created By" should read "Lovingly Created By".
