### ISSUE TITLE
New notification system

### ISSUE THREAD

**Issue by foresthoffman** [TheMacLab/game-on#116]
I tinkered with a new notification system that I believe would be far cleaner and more intuitive for us to expand and style. Currently the notification system is messy. Each notification get's output via PHP on the page along with it's own `<script>` tag (which all call the same function). We have to keep track of how many notifications there are in a global PHP variable. The variable then allows us to properly space the absolute positioned notifications on the screen.

Imagine not having to deal with any of that...Wouldn't that be nice? :D

The new notification system involves having a single notification box that is attached to the top-right of the window. The notification function will simply append a notification block—wrapped in a list item—to the notification list contained in the notification box. The benefit being that the notifications take care of themselves, and you don't have to worry about spacing or anything like that.

Here's the client-side of the notification system that I prototyped: [on codepen](http://codepen.io/foresthoffman/pen/oxwwBE)

Try playing with the heights of the notifications (change the parameters of the function calls attached to the buttons). The list will automatically adjust itself, because it and its children are on the block-level of the page, even though the notification container is fixed to the top-right of the screen.

**Comment by foresthoffman** [comment]
I also prototyped [another version](http://codepen.io/foresthoffman/pen/YqgbmB) of the notification system using AJAX. I simulated the server side code in JavaScript to make it easier to visualize.

**Comment by matthewm1970** [comment]
Looks good from a user standpoint and the coding approach sounds far cleaner.  I especially salivated at the image notification (for badges).
