### ISSUE TITLE
Failed tests award full rewards

### ISSUE THREAD

**Issue by foresthoffman** [TheMacLab/game-on#158]
From AEE:

> I've been attempting to use the "Test" option with the "Loot Modifier" set at 50. For some reason it still is granting the full credit no matter how many the student gets wrong. It will tell the student which questions are wrong and then they will have a chance to correct the mistake. Any ideas why this is happening?

According to this, tests apparently aren't reducing rewards after a user has failed multiple times.

**Comment by skocko** [comment]
I think they're misunderstanding how it works. I've made 6 different quests—no cloning or undoing stages—and the rewards are NEVER awarded with the Test Loot button checked, 50 as the Modifier, with 1, 2, or 3 questions (tried em all). Right or wrong answers have no affect on the total loot. It always adds the standard loot and ignores the Test Loot setting. Go figure. 

Test Loot is broken.
