### ISSUE TITLE
Create a 'item_count' column in the 'go' db table.

### ISSUE THREAD

**Issue by foresthoffman** [TheMacLab/game-on#31]
The column will contain the counts store-bought and rewarded items.  The 'count' parameter for the go_add_post() function in go_pnc.php is being misused for counting the quantities of store items.  The 'count' parameter and 'count' column in the 'go' table in the database is intended to be used for counting the amount of times a test has been failed, only.  A parameter and variable need to be added to go_add_post() and a column in the 'go' table, specifically for use by store items, as having one table column serve two purposes is very bad practice.  This is an absolute must, but **it can be held off until the end of the current school year** (2014/2015), as moving around the functionality for the table columns will create unwanted results.  

For example, a student that had reached the purchase cap for an item would be able to continue buying the item, as the quantity that they had purchased stored in the database would no longer be the value being checked by the store item purchase code.  That would allow the student to continue purchasing items up to the purchase limit, as if they had not purchased any items in the first place.

**Comment by swiftlee** [comment]
tgameco and I are taking a look into this.

**Comment by TGameCo** [comment]
Can confirm, We'll be looking at this
