### ISSUE TITLE
Professions in Clipboard issue

### ISSUE THREAD

**Issue by foresthoffman** [TheMacLab/game-on#40]
[Click](http://edex.adobe.com/group/game-on/discussion/899fb684/#comment-435e098a-d56b-4a46-a63e-ce75676e3d47)

This needs to be confirmed as a bug.

**Comment by vuongaustin** [comment]
I do not believe this is a bug currently.  Tried to replicate, but professions stayed even if I left the page.

**Comment by skocko** [comment]
The Mac Lab students report no such problem.

But why aren't we discussing this on slack?

-----

Mike Skocko
Valhalla High School Mac Lab | 619 593-5446
New Media Arts Teacher | Tech Coordinator | Adobe Education Leader
Website <http://maclab.guhsd.net> | Student Gallery
<https://www.behance.net/gallery/18308271/Mike-Skocko> | Game On
<http://maclab.guhsd.net/game-on/> | @themaclab
<http://twitter.com/themaclab>

**Comment by vuongaustin** [comment]
I wanted to leave the comment here in case anybody was looking into trying to replicate this bug.  Just because I couldn't replicate it doesn't mean it doesn't happen.
