### ISSUE TITLE
Add Bar Customization

### ISSUE THREAD

**Issue by vuongaustin** [TheMacLab/game-on#79]
Choose which forms of currency are available for the student to add to their own accounts. (i.e. Minutes only, Minutes & Gold, Minutes & Gold & Exp, etc.)

**Comment by foresthoffman** [comment]
@mansourgina is taking this one over. 

The `Admin Bar > Add Switch` option will contain sub menus for users and admins. Each submenu will contain additional options for each currency type to be displayed in the add bar.

The `Add Switch` option will be off by default, and the `Add Switch > Admins` option will be on by default (that includes each of the currency type options.

If a parent option is deselected, its children will not be displayed. Look at the `Additional Options > Data Reset` option for an example.

Here's a better way of looking at the layout of the options:
```
Add Switch (OFF BY DEFAULT)
    Users (OFF BY DEFAULT)
        Experience
        Gold
        Honor
        Damage
        Minutes
    Admins (ON BY DEFAULT)
        Experience
        Gold
        Honor
        Damage
        Minutes
```
